name: Build Windows (Manual)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Build (NSIS + Portable)
        run: npx electron-builder --win nsis portable --publish never

      - name: Make SHA256SUMS.txt
        shell: pwsh
        run: |
         $tmp = Join-Path $env:RUNNER_TEMP 'SHA256SUMS.txt'
         Remove-Item -Force $tmp -ErrorAction SilentlyContinue

         Get-ChildItem build_out -File -Recurse |
         Where-Object { $_.Name -ne 'SHA256SUMS.txt' } |
         ForEach-Object {
         (Get-FileHash $_.FullName -Algorithm SHA256).Hash + "  " + $_.Name
         } | Out-File $tmp -Encoding ascii

         Move-Item -Force $tmp (Join-Path 'build_out' 'SHA256SUMS.txt')

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chordalift-win
          path: build_out/**
